  
arch: amd64
os: linux
dist: focal
sudo: required

language: c

compiler: gcc

addons:
  apt: &common_apt
    config:
      retries: true
    packages: &common_packages
    - cmake
    - valgrind
    - cppcheck
    - libpqxx-dev
    - libboost-all-dev

script:
  - cd scripts
  - bash travis.sh

