  
arch: amd64
os: linux
dist: focal
sudo: required

language: c

compiler: gcc

install:
  - sudo apt-get install valgrind
  - sudo apt-get install cppcheck
  - sudo pip install cpplint
  - sudo apt-get install -f libboost-all-dev
  - sudo apt-get install -y libpqxx-dev

script:
  - cd scripts
  - bash travis.sh

