version: 2

jobs:
  test-valgrind:
    machine:
        image: ubuntu-2004:202008-01
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Extract build.tar.xz
          command: tar -xf build.tar.xz
      - run:
          name: Test executable
          command: ls
      - run:
          name: run ctest
          command: |
                  ls
                  cd build
                  valgrind --tool=memcheck --leak-check=full ctest

  build:
    machine:
        image: ubuntu-2004:202008-01
    parameters:
      label:
        type: string
        default: ubuntu2004build
    steps:
      - run:
            name: Installing dependencies
            command: |
              sudo apt -y -q update
              sudo apt -y -q install cmake
              sudo apt -y -q install valgrind
              sudo apt -y -q install cppcheck
              sudo apt -y -q install python3-pip
              sudo pip3 install cpplint
              sudo apt -y -q install libboost-all-dev
              sudo apt -y -q install libpqxx-dev 
      - checkout
      - run: 
          name: CPPCHECK
          command: |
            cppcheck --enable=all --language=c++ visionLib/test/*.cpp --suppress=missingInclude --suppress=unusedFunction 
            cppcheck --enable=all --language=c++ visionLib/clientHandler/source/*.cpp --suppress=missingInclude --suppress=unusedFunction
            cppcheck --enable=all --language=c++ visionLib/database/source/*.cpp --suppress=missingInclude --suppress=unusedFunction
            cppcheck --enable=all --language=c++ visionLib/httpClient/source/*.cpp --suppress=missingInclude --suppress=unusedFunction
            cppcheck --enable=all --language=c++ visionLib/httpServer/source/*.cpp --suppress=missingInclude --suppress=unusedFunction --suppress=useStlAlgorithm
            cppcheck --enable=all --language=c++ visionLib/logger/source/*.cpp --suppress=missingInclude --suppress=unusedFunction
            cppcheck --enable=all --language=c++ visionLib/terminalClient/source/*.cpp --suppress=missingInclude --suppress=unusedFunction
            cppcheck --enable=all --language=c++ visionLib/terminalHandler/source/*.cpp --suppress=missingInclude --suppress=unusedFunction
            cppcheck --enable=all --language=c++ visionLib/terminalServer/source/*.cpp --suppress=missingInclude --suppress=unusedFunction
            cppcheck --enable=all --language=c++ visionLib/terminalHandler/source/*.cpp --suppress=missingInclude --suppress=unusedFunction

      - run: 
          name: CPPLINT
          command: |
            cpplint --extensions=cpp visionLib/test/*.cpp 
            cpplint --extensions=cpp visionLib/clientHandler/source/*.cpp
            cpplint --extensions=cpp visionLib/database/source/*.cpp
            cpplint --extensions=cpp visionLib/httpClient/source/*.cpp
            cpplint --extensions=cpp visionLib/httpServer/source/*.cpp
            cpplint --extensions=cpp visionLib/logger/source/*.cpp
            cpplint --extensions=cpp visionLib/terminalClient/source/*.cpp
            cpplint --extensions=cpp visionLib/terminalHandler/source/*.cpp
            cpplint --extensions=cpp visionLib/terminalServer/source/*.cpp
            cpplint --extensions=cpp visionLib/terminalHandler/source/*.cpp
      - run: 
            name: CMAKE
            command: |
                rm -rf build
                mkdir build && cd build
                cmake .. 
      - run: 
            name: Build folder
            command: |
             cd build
             ls
      - run: 
            name: MAKE
            command: |
             cd build && make
      - run:
          name: Create a tarball
          command: tar -cJf build.tar.xz build
      - persist_to_workspace:
          root: .
          paths:
            - build.tar.xz
            
    
workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test-valgrind:
          requires:
            - build
      
