version: 2

jobs:
  build:
    machine: # executor type
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install aptitude
            aptitude install valgrind
            aptitude install cppcheck
            sudo pip install cpplint
            aptitude install -f libboost-all-dev
            aptitude install -y libpqxx-dev
      - run:
          name: test
          command: pwd
    
