version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Installing GIT
          command: 'apt-get update && apt-get install -y git'
      - run:
          name: Installing PIP
          command: 'apt-get update && apt-get install -y python3-pip'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: CMAKE version check
          command: 'cmake --version'
      - run:
          name: Installing VALGRIND
          command: 'apt-get update && sudo apt-get install -y valgrind'
      - run:
          name: Installing CPPCHECK
          command: 'apt-get update && sudo apt-get install -y cppcheck'
      - run:
          name: Installing CPPLINT
          command: 'sudo pip3 install cpplint'
      - run: 
          name: Installing BOOST
          command: 'apt-get update && sudo apt-get install -y libboost-all-dev'
      - run: 
          name: Installing PQXX
          command: 'apt-get update && sudo apt-get install -y libpqxx-dev'
      - run: 
          name: CPPCHECK
          command: |
            cppcheck --enable=all --language=c++ visionLib/test/*.cpp --suppress=missingInclude --suppress=unusedFunction 
            cppcheck --enable=all --language=c++ visionLib/clientHandler/source/*.cpp --suppress=missingInclude --suppress=unusedFunction
            cppcheck --enable=all --language=c++ visionLib/database/source/*.cpp --suppress=missingInclude --suppress=unusedFunction
            cppcheck --enable=all --language=c++ visionLib/httpClient/source/*.cpp --suppress=missingInclude --suppress=unusedFunction
            cppcheck --enable=all --language=c++ visionLib/httpServer/source/*.cpp --suppress=missingInclude --suppress=unusedFunction --suppress=useStlAlgorithm
            cppcheck --enable=all --language=c++ visionLib/logger/source/*.cpp --suppress=missingInclude --suppress=unusedFunction
            cppcheck --enable=all --language=c++ visionLib/terminalClient/source/*.cpp --suppress=missingInclude --suppress=unusedFunction
            cppcheck --enable=all --language=c++ visionLib/terminalHandler/source/*.cpp --suppress=missingInclude --suppress=unusedFunction
            cppcheck --enable=all --language=c++ visionLib/terminalServer/source/*.cpp --suppress=missingInclude --suppress=unusedFunction
            cppcheck --enable=all --language=c++ visionLib/terminalHandler/source/*.cpp --suppress=missingInclude --suppress=unusedFunction

      - run: 
          name: CPPLINT
          command: |
            cpplint --extensions=cpp visionLib/test/*.cpp 
            cpplint --extensions=cpp visionLib/clientHandler/source/*.cpp
            cpplint --extensions=cpp visionLib/database/source/*.cpp
            cpplint --extensions=cpp visionLib/httpClient/source/*.cpp
            cpplint --extensions=cpp visionLib/httpServer/source/*.cpp
            cpplint --extensions=cpp visionLib/logger/source/*.cpp
            cpplint --extensions=cpp visionLib/terminalClient/source/*.cpp
            cpplint --extensions=cpp visionLib/terminalHandler/source/*.cpp
            cpplint --extensions=cpp visionLib/terminalServer/source/*.cpp
            cpplint --extensions=cpp visionLib/terminalHandler/source/*.cpp
      - run: 
            name: CMAKE
            command: |
                rm -rf build
                mkdir build && cd build
                cmake .. 
      - run: 
            name: MAKE
            command: |
             pwd
             ls
      - run: 
            name: MAKE
            command: |
             cd build
             ls
      - run: 
            name: MAKE
            command: 'make' 
   
