version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Installing VALGRIND
          command: 'apt-get update && sudo apt-get install -y valgrind'
      - run:
          name: Creating Binary Files
          command: 'apt-get update && sudo apt-get install -y cppcheck'
      - run: 
          name: Creating Binary Files
          command: 'apt-get update && sudo apt-get install -f libboost-all-dev'
      - run: 
          name: Creating Binary Files
          command: 'apt-get update && sudo apt-get install -y libpqxx-dev'
